name: blog_turismo_app
description: "Aplicación de blog turístico con perfiles de visitante y publicador"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.6.0
  firebase_storage_web: ^3.9.0
  image_picker: ^1.0.7
  image_picker_for_web: ^2.1.1
  intl: ^0.18.1
  geolocator: ^11.0.0
  url_launcher: ^6.3.0
  cupertino_icons: ^1.0.8
  image: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
